import { createServerClient } from '@supabase/ssr'
import { createClient as createSupabaseClient, type SupabaseClient } from '@supabase/supabase-js'
import { cookies } from 'next/headers'
//creates server client using env keys
export async function createClient() {
  const cookieStore = await cookies()

  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return cookieStore.getAll()
        },
        //sets site cookies
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) =>
            cookieStore.set(name, value, options)
          )
        },
      },
    }
  )
}

//admin client using service role key -> BYPASSES RLS
//Daily Challenge reads and writes server only answers table
let adminClient: SupabaseClient | null = null
export function createAdminClient() {
  //created once on first use, then reused
  adminClient ??= createSupabaseClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false, autoRefreshToken: false } }   //no browser session on the server
  )
  return adminClient
}
 

//Qiskit service
/** POST to the Python/Qiskit service with internal API key, and return a JSON response */
export async function qiskit<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(`${process.env.QISKIT_SERVICE_URL}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-api-key': process.env.INTERNAL_API_KEY! },
    body: JSON.stringify(body),
    cache: 'no-store',                         
  })
  if (!res.ok) throw new Error(`Qiskit service ${path} failed: ${res.status}`)
  return res.json() as Promise<T>
}
 

//Daily Challenge helpers
/** the day's date (YYYY-MM-DD) in Melbourne time, so a "day" matches users' local time*/
export function melbourneDate(): string {
  //en-CA locale formats dates as YYYY-MM-DD
  return new Intl.DateTimeFormat('en-CA', { timeZone: 'Australia/Melbourne' }).format(new Date())
}
 
/**
 * turn a string into a stable integer seed (FNV-1a hash).
 * the same string always gives the same number, e.g. "user:2026-09-30:1".
 */
export function seedFrom(s: string): number {
  let h = 2166136261                                          //FNV offset basis
  for (const c of s) h = Math.imul(h ^ c.charCodeAt(0), 16777619)  //XOR each character, multiply by FNV prime
  return h >>> 0                                              //force an unsigned 32 bit result
}
 
/**
 * small seeded random number generator (mulberry32).
 * returns a function that gives numbers in [0, 1); the same seed always gives the same
 * sequence, so things like option shuffles can be reproduced
 */
export function seededRandom(seed: number) {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0                  //advance the internal state
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)        //bit mixing steps of the mulberry32 algorithm
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296   //scale the 32 bit result to [0, 1)
  }
}
 
//categories generated by the Python service. One is picked at random per user, day and tier.
export const PYTHON_TYPES = [
  'bb84_eve',
  'sifting',
  'state_evolution',
  'normalisation',
  'gate_simplification',
] as const
//multiple choice on learning content. Only eligible at tier 1 and only once the user
//has completed a module that has content, so it will be skipped until content exists
export const MODULE_MCQ = 'module_mcq'
//maximum attempts per challenge tier before worked solution is revealed
export const MAX_ATTEMPTS = 3
 