"""
BB84 key exchange core logic imported from docs/sprint-1/bb84-poc/bb84_poc.py (build_qubit_circuit, transmit,
run_bb84). Everything here is called from the FastAPI endpoint instead. Measurement randomness is seeded now rather than 
classical bit/basis choices so a seed produces a fully reproducible run. 
"""

import random

from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator

SIM = AerSimulator()

# Basis encoding used throughout:
#   0 = rectilinear basis  (Z-basis: states |0>, |1>)
#   1 = diagonal basis     (X-basis: states |+>, |->)
RECTILINEAR, DIAGONAL = 0, 1
BASIS_SYMBOL = {RECTILINEAR: "+", DIAGONAL: "x"}


def build_qubit_circuit(bit: int, prep_basis: int, meas_basis: int) -> QuantumCircuit:
    """Returns a Qiskit circuit that prepares one qubit in `prep_basis` encoding
    `bit`, then measures it in `meas_basis`."""
    qc = QuantumCircuit(1, 1)

    if bit == 1:
        qc.x(0)
    if prep_basis == DIAGONAL:
        qc.h(0)

    qc.barrier(label="send")

    if meas_basis == DIAGONAL:
        qc.h(0)
    qc.measure(0, 0)
    return qc


def transmit(bit: int, prep_basis: int, meas_basis: int, seed: int | None = None) -> int: #seed number is optional, defaults to 'None' if not given
    """Run one qubit's circuit on the simulator and return the measured bit.
    """
    result = SIM.run(
        build_qubit_circuit(bit, prep_basis, meas_basis),   #build a circuit so simulator can run
        shots=1,                                            #run simulation once and give one result instead of repeated tries 
        memory=True,                                        #remember result of a particular run
        seed_simulator=seed,                                #seed input used to determine outcome of measurement when bases don't match
                                                            #if seed is none, generates random outcome on its own 
                               
    ).result()
    return int(result.get_memory()[0])


def run_bb84(
    n: int,
    eavesdrop: bool,
    rng: random.Random,                 #whichever role is not user_role gets its bits/basees generated by rng
    user_role: str | None = None,       #when user_role is set, their bits/bases come from user_bases / user_bits instead of rng
    user_bases: list[int] | None = None,
    user_bits: list[int] | None = None,
) -> dict:
    
    """
    Execute a full BB84 exchange over n qubits and return every stage's data.

    Flow: preparation -> (optional Eve) -> measurement -> basis reconciliation
          (sifting) -> error estimation (QBER) -> sifted key.

    Also computes baseline_qber: the QBER Alice and Bob would have measured on
    this bit stream had nobody intercepted it. When eavesdrop = False,
    this is just qber again (nothing was intercepted either way, so
    there's only one measurement to look at). When eavesdrop = True, Bob's
    no-eve measurement is re-simulated directly against Alice's original qubit.
    On this noiseless simulator it should come out essentially 0.0 every time.

    returns both Alice's and Bob's bits for the portion of the sifted key,
    since key post-processing needs both sides to reconcile a shared secret key.
    """

    alice_bits = list(user_bits) if user_role == "alice" else [rng.randint(0, 1) for _ in range(n)]
    alice_bases = list(user_bases) if user_role == "alice" else [rng.randint(0, 1) for _ in range(n)]
    bob_bases = list(user_bases) if user_role == "bob" else [rng.randint(0, 1) for _ in range(n)]
    eve_bases = (
        (list(user_bases) if user_role == "eve" else [rng.randint(0, 1) for _ in range(n)])
        if eavesdrop else None
    )

    # seed needed for each measurement
    # Every time the quantum simulator measures a qubit in the wrong basis (mismatch), outcome is either 0 or 1.
    # To make this repeatable, assign seed for a particular mismatched measurement.

    # for each of Alice's n qubits there are up to 3 measurements that might happen-
    # Bob's real measurement, Eve's (if listening), and Bob's counterfactual
    # "no Eve" measurement (only taken when eavesdrop is True) used purely to
    # compute baseline_qber below, so at most we need 3 seeds per qubit
    sim_seeds = [rng.randint(0, 2**31 - 1) for _ in range(3 * n)]  # e.g. n = 3 qubits sent, 3 * 3 = 9 seeds needed total

    bob_results = []
    bob_baseline_results = []  # what Bob would've measured with no Eve - used only for baseline_qber
    eve_bits = [] if eavesdrop else None
    for i in range(n):
        bit, basis = alice_bits[i], alice_bases[i]
        if eavesdrop:
            eve_bit = transmit(bit, basis, eve_bases[i], seed=sim_seeds[3 * i])
            eve_bits.append(eve_bit)
            bit, basis = eve_bit, eve_bases[i]
        bob_results.append(transmit(bit, basis, bob_bases[i], seed=sim_seeds[3 * i + 1]))

        if eavesdrop:
            # counterfactual: Bob measuring Alice's original qubit directly, as if Eve
            # had never intercepted it. Never fed into the real exchange above 
            # this result exists solely to compute baseline_qber.
            bob_baseline_results.append(
                transmit(alice_bits[i], alice_bases[i], bob_bases[i], seed=sim_seeds[3 * i + 2])
            )
        else:
            # nothing was intercepted, so Bob's real measurement already is the
            # no-Eve measurement no need to re-simulate it a second time.
            bob_baseline_results.append(bob_results[-1])

    sifted_idx = [i for i in range(n) if alice_bases[i] == bob_bases[i]]
    alice_key = [alice_bits[i] for i in sifted_idx]
    bob_key = [bob_results[i] for i in sifted_idx]
    bob_baseline_key = [bob_baseline_results[i] for i in sifted_idx]

    sample_size = len(sifted_idx) // 2  #half the bits in the sifted key will be publicly compared
    errors = sum(1 for j in range(sample_size) if alice_key[j] != bob_key[j]) #within sample size, count how many positions disagree between Alice and Bob
    qber = (errors / sample_size) if sample_size else 0.0   #turn error count into % (if sample size = 0, return 0 instead of dividing by 0)

    baseline_errors = sum(1 for j in range(sample_size) if alice_key[j] != bob_baseline_key[j])
    baseline_qber = (baseline_errors / sample_size) if sample_size else 0.0

    # Bits not sacrificed for QBER estimation used in key post-processing as these are still secret at this point
    alice_remaining = alice_key[sample_size:]
    bob_remaining = bob_key[sample_size:]

    return {
        "n": n,
        "eavesdrop": eavesdrop,
        "alice_bits": alice_bits,
        "alice_bases": alice_bases,
        "bob_bases": bob_bases,
        "eve_bases": eve_bases,
        "eve_bits": eve_bits,
        "bob_results": bob_results,
        "sifted_idx": sifted_idx,
        "alice_key": alice_key,
        "bob_key": bob_key,
        "sample_size": sample_size,
        "errors": errors,
        "qber": qber,
        "baseline_qber": baseline_qber,
        "alice_remaining": alice_remaining,
        "bob_remaining": bob_remaining,
    }
